name: SonarQube Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: "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"
          SONAR_TOKEN: "sqp_aa5210a7a86bd73fed62fcce7e7e9678874cd721"
          SONAR_HOST_URL: "https://0b6dd7580fed417c-197-153-106-8.serveousercontent.com"
          SONAR_USER_HOME: /opt/sonar-scanner/.sonar
        with:
          args: >
            -Dsonar.projectKey=TEST
            -Dsonar.sources=src/main/resources
            -Dsonar.verbose=true
